apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: converg-dataset-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi # the storage size depends on the chosen experiment parameters (e.g., versions, products and variabilities)