apiVersion: batch/v1
kind: Job
metadata:
  name: dataset-generation-job-alt
spec:
  template:
    spec:
      containers:
      - name: bsbm-generator-alt
        image: vcity/bsbm
        imagePullPolicy: Always
        args: ["generate-n", "250", "1", "1", "0"] # 250 versions, 1 products, step of 1, variability of 0
        env:
        - name: DATA_DESTINATION
          value: "data-alt"
        volumeMounts:
        - name: converg-dataset-volume
          mountPath: /app/data
      volumes:
      - name: converg-dataset-volume
        persistentVolumeClaim:
          claimName: converg-dataset-pvc
      restartPolicy: Never