apiVersion: batch/v1
kind: Job
metadata:
  name: dataset-generation-job
spec:
  template:
    spec:
      containers:
      - name: bsbm-generator
        image: vcity/bsbm
        imagePullPolicy: Always
        args: ["generate-n", "4", "2", "2", "2"] # 4 versions, 2 products, step of 2, variability of 2
        volumeMounts:
        - name: converg-dataset-volume
          mountPath: /app/data
      volumes:
      - name: converg-dataset-volume
        persistentVolumeClaim:
          claimName: converg-dataset-pvc
      restartPolicy: Never