apiVersion: batch/v1
kind: Job
metadata:
  name: dataset-generation-job
spec:
  template:
    spec:
      containers:
      - name: bsbm-generator
        image: vcity/bsbm
        args: ["generate-n", "50", "10", "10", "5"] # 50 versions, 10 products, step of 10, variability of 5
        volumeMounts:
        - name: converg-dataset-volume
          mountPath: /app/data
      volumes:
      - name: converg-dataset-volume
        persistentVolumeClaim:
          claimName: converg-dataset-pvc
      restartPolicy: Never