apiVersion: v1
kind: ConfigMap
metadata:
  name: import-script-configmap
data:
  import-dataset-theoretical.sh: |
    # /bin/bash

    cd /app/data/theoretical || exit
    echo "-------------------------------------------------------------- [BEGIN IMPORT TRIPLE] --------------------------------------------------------------"
    printf "\n%s$(date +%FT%T) - [Triple Store] Dataset import started."

    ## BSBM tagged data
    find . -type f -name "*.trig" -print0 | while IFS= read -r -d '' file; do
        printf "%s\n$(date +%FT%T) - [Triple Store] $file."
        start=$(date +%s%3N)
        curl -X POST --location 'http://blazegraph:9999/blazegraph/sparql' \
            --header 'Content-Type:application/x-trig' \
            --connect-timeout 180 \
            --data-binary @"$file"
        end=$(date +%s%3N)
        printf "\n%s$(date +%FT%T) - [Measure] (Import BG $file):$((end - start))ms;"
    done

    printf "\n%s$(date +%FT%T) - [Triple Store] Dataset import completed."
    echo "--------------------------------------------------------------- [END IMPORT TRIPLE] ---------------------------------------------------------------"
  import-dataset-relational.sh: |
    # /bin/bash

    cd /app/data/relational || exit
    echo "------------------------------------------------------------ [BEGIN IMPORT RELATIONAL] ------------------------------------------------------------"
    printf "\n%s$(date +%FT%T) - [quads-loader] Dataset import started."

    ## BSBM tagged data
    ### Import the versions of BSBM

    find . -type f -name "*.ttl.relational.trig" -print0 | while IFS= read -r -d '' file
    do
        printf "\n%s$(date +%FT%T) - [quads-loader] Version $file"
        start=$(date +%s%3N)
        curl --location 'http://quads-loader:8080/import/version' \
          --header 'Content-Type: multipart/form-data' \
          --connect-timeout 180 \
          --form file=@"$file"
        end=$(date +%s%3N)
        printf "\n%s$(date +%FT%T) - [Measure] (Import STS $file):$((end-start))ms;"
    done

    printf "\n%s$(date +%FT%T) - [quads-loader] Dataset import completed."

    ### Condense dataset
    printf "\n%s$(date +%FT%T) - [quads-loader] Dataset condensation started."
    curl --location 'http://quads-loader:8080/import/condense'
    printf "\n%s$(date +%FT%T) - [quads-loader] Dataset condensation completed."

    echo "------------------------------------------------------------- [END IMPORT RELATIONAL] -------------------------------------------------------------"
