apiVersion: batch/v1
kind: Job
metadata:
  name: dataset-importer-job
spec:
  template:
    spec:
      containers:
      - name: dataset-importer
        image: ubuntu:latest
        command: ["/bin/bash", "-c", "apt-get update && apt-get install -y curl && /app/import-dataset.sh"]
        volumeMounts:
        - name: converg-dataset-volume
          mountPath: /app/data
        - name: import-script-configmap-volume
          mountPath: /app
      volumes:
      - name: converg-dataset-volume
        persistentVolumeClaim:
          claimName: converg-dataset-pvc
      - name: import-script-configmap-volume
        configMap:
          name: import-script-configmap
          defaultMode: 0744
      restartPolicy: Never