apiVersion: batch/v1
kind: Job
metadata:
  name: theoretical-dataset-importer-job-alt
spec:
  template:
    spec:
      containers:
      - name: dataset-importer-theoretical-alt
        image: ubuntu:latest
        command: ["/bin/bash", "-c", "apt-get update && apt-get install -y curl && /app/scripts/import-dataset-theoretical-alt.sh 4"]
        volumeMounts:
        - name: converg-dataset-volume
          mountPath: /app/data
        - name: import-script-configmap-volume
          mountPath: /app/scripts
      volumes:
      - name: converg-dataset-volume
        persistentVolumeClaim:
          claimName: converg-dataset-pvc
      - name: import-script-configmap-volume
        configMap:
          name: import-script-configmap
          defaultMode: 0744
      restartPolicy: Never