apiVersion: batch/v1
kind: Job
metadata:
  name: dataset-transformer-job
spec:
  template:
    spec:
      containers:
      - name: dataset-transformer-relational
        image: vcity/quads-creator
        imagePullPolicy: Always
        args: ["/app/data/data/relational", "/app/data/data", "*", "relational", "BSBM"]
        volumeMounts:
        - name: converg-dataset-volume
          mountPath: /app/data
        resources:
          requests:
            memory: "8Gi"
            cpu: "2"
          limits:
            memory: "16Gi"
            cpu: "2"
      - name: dataset-transformer-theoretical
        image: vcity/quads-creator
        imagePullPolicy: Always
        args: ["/app/data/data/theoretical", "/app/data/data", "*", "theoretical", "BSBM"]
        volumeMounts:
        - name: converg-dataset-volume
          mountPath: /app/data
        resources:
          requests:
            memory: "8Gi"
            cpu: "2"
          limits:
            memory: "16Gi"
            cpu: "2"

      - name: dataset-transformer-relational-alt
        image: vcity/quads-creator
        imagePullPolicy: Always
        args: ["/app/data/data-alt/relational", "/app/data/data-alt", "*", "relational", "BSBM-alt"]
        volumeMounts:
        - name: converg-dataset-volume
          mountPath: /app/data
        resources:
          requests:
            memory: "8Gi"
            cpu: "2"
          limits:
            memory: "16Gi"
            cpu: "2"
      - name: dataset-transformer-theoretical-alt
        image: vcity/quads-creator
        imagePullPolicy: Always
        args: ["/app/data/data-alt/theoretical", "/app/data/data-alt", "*", "theoretical", "BSBM-alt"]
        volumeMounts:
        - name: converg-dataset-volume
          mountPath: /app/data
        resources:
          requests:
            memory: "8Gi"
            cpu: "2"
          limits:
            memory: "16Gi"
            cpu: "2"
      volumes:
      - name: converg-dataset-volume
        persistentVolumeClaim:
          claimName: converg-dataset-pvc
      restartPolicy: Never