apiVersion: batch/v1
kind: Job
metadata:
  name: dataset-transformer-job
spec:
  template:
    spec:
      containers:
      - name: dataset-transformer-relational
        image: vcity/quads-creator
        args: ["/app/data/relational", "/app/data", "*", "relational", "BSBM"]
        volumeMounts:
        - name: converg-dataset-volume
          mountPath: /app/data
        resources:
          requests:
            memory: "16Gi"
            cpu: "4"
          limits:
            memory: "32Gi"
            cpu: "4"
      - name: dataset-transformer-theoretical
        image: vcity/quads-creator
        args: ["/app/data/theoretical", "/app/data", "*", "theoretical", "BSBM"]
        volumeMounts:
        - name: converg-dataset-volume
          mountPath: /app/data
        resources:
          requests:
            memory: "16Gi"
            cpu: "4"
          limits:
            memory: "32Gi"
            cpu: "4"
      volumes:
      - name: converg-dataset-volume
        persistentVolumeClaim:
          claimName: converg-dataset-pvc
      restartPolicy: Never