apiVersion: batch/v1
kind: Job
metadata:
  name: dataset-transformer-job
spec:
  template:
    spec:
      containers:
      - name: dataset-transformer
        image: harbor.pagoda.os.univ-lyon1.fr/ud-evolution/quads-creator
        args: ["/app/data/theor", "/app/data", "*", "ttl", "theoretical", "BSBM"]
        volumeMounts:
        - name: converg-dataset-volume
          mountPath: /app/data
        resources:
          limits:
            memory: "8Gi"
            cpu: "8"
      volumes:
      - name: converg-dataset-volume
        persistentVolumeClaim:
          claimName: converg-dataset-pvc
      restartPolicy: Never