
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: blazegraph
spec:
  serviceName: blazegraph
  selector:
    matchLabels:
      app: blazegraph
  template:
    metadata:
      labels:
        app: blazegraph
    spec:
      containers:
      - name: blazegraph
        image: vcity/blazegraph-cors
        imagePullPolicy: Always
        env:
        - name: BLAZEGRAPH_QUADS
          value: "true"
        - name: BLAZEGRAPH_TIMEOUT
          value: "600000"
        - name: BLAZEGRAPH_MEMORY
          value: "32G"
        resources:
          requests:
            memory: "16Gi"
            cpu: "8"
          limits:
            memory: "64Gi"
            cpu: "32"
        ports:
        - containerPort: 8080
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: 
          - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
---
# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: blazegraph
spec:
  selector:
    app: blazegraph
  type: ClusterIP
  ports:
  - name: blazegraph
    protocol: TCP
    port: 9999
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blazegraph-exporter
spec:
  selector:
    matchLabels:
      app: blazegraph-exporter
  template:
    metadata:
      labels:
        app: blazegraph-exporter
    spec:
      containers:
        - name: blazegraph-exporter
          image: harbor.pagoda.os.univ-lyon1.fr/ud-evolution/blazegraph-exporter:v1.0.2
          ports:
            - containerPort: 9400
              name: metrics
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
          env: 
            - name: BASE_URL
              value: "http://blazegraph:9999"
            - name: PORT_EXPORTER
              value: "9400"
---
apiVersion: v1
kind: Service
metadata:
  name: blazegraph-exporter-service
  labels:
    app: blazegraph-exporter-service
spec:
  selector:
    app: blazegraph-exporter
  ports:
    - name: metrics
      protocol: TCP
      port: 9400
      targetPort: 9400
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: blazegraph-db
  labels:
    app: ud-evolution
spec:
  selector:
    matchLabels:
      app: blazegraph-exporter-service
  endpoints:
  - targetPort: 9400
    path: /metrics
    interval: 15s