
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blazegraph
spec:
  selector:
    matchLabels:
      app: blazegraph
  template:
    metadata:
      labels:
        app: blazegraph
    spec:
      containers:
      - name: blazegraph
        image: vcity/blazegraph-cors
        imagePullPolicy: Always
        env:
        - name: BLAZEGRAPH_QUADS
          value: "true"
        - name: BLAZEGRAPH_TIMEOUT
          value: "180000"
        - name: BLAZEGRAPH_MEMORY
          value: "32G"
        resources:
          limits:
            memory: "32Gi"
            cpu: "8"
        ports:
        - containerPort: 8080
---
# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: blazegraph
spec:
  selector:
    app: blazegraph
  type: ClusterIP
  ports:
  - name: blazegraph
    protocol: TCP
    port: 9999
    targetPort: 8080
