
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quads-loader
spec:
  selector:
    matchLabels:
      app: quads-loader
  template:
    metadata:
      labels:
        app: quads-loader
    spec:
      containers:
      - name: quads-loader
        image: vcity/quads-loader
        imagePullPolicy: Always
        env:
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql-db-secret
              key: POSTGRES_PASSWORD
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgresql-db-secret
              key: POSTGRES_USER
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            secretKeyRef:
              name: postgresql-db-secret
              key: DATASOURCE_URL
        resources:
          limits:
            memory: "64Gi"
            cpu: "32"
          requests:
            memory: "16Gi"
            cpu: "8"
        ports:
        - containerPort: 8080
        - containerPort: 9400
---
# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: quads-loader
  labels:
    app: quads-loader
spec:
  selector:
    app: quads-loader
  type: ClusterIP
  ports:
  - name: quads-loader
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: metrics
    protocol: TCP
    port: 9400
    targetPort: 9400
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: quads-loader
  labels:
    app: ud-evolution
spec:
  selector:
    matchLabels:
      app: quads-loader
  endpoints:
  - targetPort: 9400
    path: /metrics
    interval: 15s