
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-versioning
spec:
  selector:
    matchLabels:
      app: demo-versioning
  template:
    metadata:
      labels:
        app: demo-versioning
    spec:
      containers:
      - name: demo-versioning
        image: harbor.pagoda.os.univ-lyon1.fr/ud-evolution/demo-versioning:v1.3.0
        imagePullPolicy: Always
        resources:
          limits:
            memory: "1Gi"
            cpu: "2"
        ports:
        - containerPort: 8000
---
# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: demo-versioning
spec:
  selector:
    app: demo-versioning
  type: ClusterIP
  ports:
  - name: demo-versioning
    protocol: TCP
    port: 80
    targetPort: 8000
