
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quads-query
spec:
  selector:
    matchLabels:
      app: quads-query
  template:
    metadata:
      labels:
        app: quads-query
    spec:
      containers:
      - name: quads-query
        image: vcity/quads-query
        imagePullPolicy: Always
        env:
        - name: DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql-db-secret
              key: POSTGRES_PASSWORD
        - name: DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgresql-db-secret
              key: POSTGRES_USER
        - name: DATASOURCE_URL
          valueFrom:
            secretKeyRef:
              name: postgresql-db-secret
              key: DATASOURCE_URL
        resources:
          limits:
            memory: "8Gi"
            cpu: "8"
        ports:
        - containerPort: 8081
---
# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: quads-query
spec:
  selector:
    app: quads-query
  type: ClusterIP
  ports:
  - name: quads-query
    protocol: TCP
    port: 8081
    targetPort: 8081
