
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quads-query-reasoning
spec:
  selector:
    matchLabels:
      app: quads-query-reasoning
  template:
    metadata:
      labels:
        app: quads-query-reasoning
    spec:
      containers:
      - name: quads-query-reasoning
        image: vcity/quads-query
        imagePullPolicy: Always
        env:
        - name: DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql-db-secret
              key: POSTGRES_PASSWORD
        - name: DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgresql-db-secret
              key: POSTGRES_USER
        - name: DATASOURCE_URL
          valueFrom:
            secretKeyRef:
              name: postgresql-db-secret
              key: DATASOURCE_URL
        - name: ENTAILMENT_REGIME
          value: "RDFS"
        resources:
          requests:
            memory: "1Gi"
            cpu: "0.5"
          limits:
            memory: "8Gi"
            cpu: "8"
        ports:
        - containerPort: 8081
        - containerPort: 9400
---
# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: quads-query-reasoning
  labels:
    app: quads-query-reasoning
spec:
  selector:
    app: quads-query-reasoning
  type: ClusterIP
  ports:
  - name: quads-query-reasoning
    protocol: TCP
    port: 8081
    targetPort: 8081
  - name: metrics
    protocol: TCP
    port: 9400
    targetPort: 9400
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: quads-query-reasoning
  labels:
    app: ud-evolution
spec:
  selector:
    matchLabels:
      app: quads-query-reasoning
  endpoints:
  - targetPort: 9400
    path: /metrics
    interval: 15s