apiVersion: v1
kind: ConfigMap
metadata:
  name: query-script-configmap
data:
  blazegraph-0.rq: |
    # Query the graph store for all quads
    SELECT ?g ?s ?p ?o WHERE {
        GRAPH ?g {
          ?s ?p ?o .
        }
        FILTER(?g != <https://github.com/VCityTeam/ConVer-G/Named-Graph#Metadata>)
    }
  blazegraph-1.rq: |
    # Query for all triples (includes quads)
    SELECT ?s ?p ?o WHERE {
        GRAPH <https://github.com/VCityTeam/ConVer-G/Named-Graph#Metadata> {
            ?s ?p ?o .
        }
    }
  blazegraph-2.rq: |
    # Query the graph store for all quads with a given subject
    SELECT ?g ?p ?o WHERE {
        GRAPH ?g {
          <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/ProductFeature287> ?p ?o .
        }
        FILTER(?g != <https://github.com/VCityTeam/ConVer-G/Named-Graph#Metadata>)
    }
  blazegraph-3.rq: |
    # Query the graph store for all quads with a given subject and a join on the subject (predicate might be equal to predicate2 and object might be equal to object2)
    SELECT ?g ?p ?o WHERE {
        GRAPH ?g {
          <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/ProductFeature287> ?p ?o ;
            ?p2 ?o2 .
        }
        FILTER(?g != <https://github.com/VCityTeam/ConVer-G/Named-Graph#Metadata>)
    }
  blazegraph-4.rq: |
    # Query the graph store for all quads with a given subject and a join on the subject (predicate might be equal to predicate2 and object might be equal to object2)
    SELECT ?graph ?predicate ?object WHERE {
        GRAPH ?graph {
          <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/ProductFeature287> ?predicate ?object ;
            ?predicate2 ?object2 .
          FILTER(?predicate != ?predicate2 && ?object != ?object2 && ?graph != <https://github.com/VCityTeam/ConVer-G/Named-Graph#Metadata>)
        }
    }
  blazegraph-5.rq: |
    # Query the graph store for all quads with a given subject and a join on the predicate and subject (object might be equal to object2)
    SELECT ?graph ?subject ?predicate ?object ?object2 WHERE {
        GRAPH ?graph {
          <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/ProductFeature287> ?predicate ?object ,
            ?object2 .
        }
        FILTER(?graph != <https://github.com/VCityTeam/ConVer-G/Named-Graph#Metadata>)
    }
  blazegraph-6.rq: |
    # Query the graph store for all quads in a specific versioned graph with a given subject and a join on the subject (predicate might be equal to predicate2 and object might be equal to object2)
    SELECT ?p ?o WHERE {
        GRAPH <https://github.com/VCityTeam/ConVer-G/Versioned-Named-Graph#a156e4f5c5cb3dda5b72fb64c4264de925a10fbdefa8ae5b7066e69027edbd48> {
          <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/ProductFeature287> ?p ?o ;
            ?p2 ?o2 .
        }
    }
