apiVersion: v1
kind: ConfigMap
metadata:
  name: query-script-configmap
data:
  converg-0.rq: |
    # Query the graph store for all quads
    SELECT ?g ?s ?p ?o WHERE {
        GRAPH ?g {
          ?s ?p ?o .
        }
    }
  converg-1.rq: |
    # Query for all metadata triples
    SELECT ?s ?p ?o WHERE {
          ?s ?p ?o .
    }
  converg-2.rq: |
    # Query the graph store for all quads with a given subject
    SELECT ?g ?p ?o WHERE {
        GRAPH ?g {
          <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/ProductFeature287> ?p ?o .
        }
    }
  converg-3.rq: |
    # Query the graph store for all quads with a given subject and a join on the subject (predicate might be equal to predicate2 and object might be equal to object2)
    SELECT ?g ?p ?o WHERE {
        GRAPH ?g {
          <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/ProductFeature287> ?p ?o ;
            ?p2 ?o2 .
        }
    }
  converg-4.rq: |
    # Query the graph store for all quads with a given subject and a join on the subject (predicate might be equal to predicate2 and object might be equal to object2)
    SELECT ?graph ?predicate ?object WHERE {
        GRAPH ?graph {
          <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/ProductFeature287> ?predicate ?object ;
            ?predicate2 ?object2 .
          FILTER(?predicate != ?predicate2 && ?object != ?object2)
        }
    }
  converg-5.rq: |
    # Query the graph store for all quads with a given subject and a join on the predicate and subject (object might be equal to object2)
    SELECT ?graph ?subject ?predicate ?object ?object2 WHERE {
        GRAPH ?graph {
          <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/ProductFeature287> ?predicate ?object ,
          ?object2 .
        }
    }
  converg-6.rq: |
    # Query the graph store for all quads in a specific versioned graph with a given subject and a join on the subject (predicate might be equal to predicate2 and object might be equal to object2)
    SELECT ?p ?o WHERE {
        GRAPH <https://github.com/VCityTeam/ConVer-G/Versioned-Named-Graph#448558e1c46da16012fc8a76f0cda0c33498b3b55c240167cec08b93ded41fc75aeff6fd52ffe7d099e87f91016be2dd6055a83b465fcc3d9867bc3605c8f8ec> {
          <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/ProductFeature287> ?p ?o ;
            ?p2 ?o2 .
        }
    }
