apiVersion: v1
kind: ConfigMap
metadata:
  name: query-script-configmap
data:
  converg-0.rq: |
    # Query the graph store for all quads
    SELECT ?g ?s ?p ?o WHERE {
        GRAPH ?g {
          ?s ?p ?o .
        }
    }
  converg-1.rq: |
    # Query for all metadata triples
    SELECT ?s ?p ?o WHERE {
          ?s ?p ?o .
    }
  converg-2.rq: |
    # Query the graph store for all quads with a given subject
    SELECT ?g ?p ?o WHERE {
        GRAPH ?g {
          <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/ProductFeature287> ?p ?o .
        }
    }
  converg-3.rq: |
    # Query the graph store for all quads with a given subject and a join on the subject (predicate might be equal to predicate2 and object might be equal to object2)
    SELECT ?g ?p ?o WHERE {
        GRAPH ?g {
          <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/ProductFeature287> ?p ?o ;
            ?p2 ?o2 .
        }
    }
  converg-4.rq: |
    # Query the graph store for all quads with a given subject and a join on the subject (predicate might be equal to predicate2 and object might be equal to object2)
    SELECT ?graph ?predicate ?object WHERE {
        GRAPH ?graph {
          <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/ProductFeature287> ?predicate ?object ;
            ?predicate2 ?object2 .
          FILTER(?predicate != ?predicate2 && ?object != ?object2)
        }
    }
  converg-5.rq: |
    # Query the graph store for all quads with a given subject and a join on the predicate and subject (object might be equal to object2)
    SELECT ?graph ?subject ?predicate ?object ?object2 WHERE {
        GRAPH ?graph {
          <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/ProductFeature287> ?predicate ?object ,
          ?object2 .
        }
    }
  converg-6.rq: |
    # Query the graph store for all quads in a specific versioned graph with a given subject and a join on the subject (predicate might be equal to predicate2 and object might be equal to object2)
    SELECT ?p ?o WHERE {
        GRAPH <https://github.com/VCityTeam/ConVer-G/Versioned-Named-Graph#d39f0e104fd4de9d4f0a04435d674c2bde498e2390e37153f33530e2ef7d080ebb634f74e136fad92f514812a04ea9c14523da8935a245c0cb1b5668c01689f8> {
          <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/ProductFeature287> ?p ?o ;
            ?p2 ?o2 .
        }
    }
  converg-7.rq: |
    SELECT ?graph ?p ?o WHERE {
        GRAPH ?vg {
          <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/ProductFeature287> ?p ?o ;
            ?p2 ?o2 .
        }
        ?vg <https://github.com/VCityTeam/ConVer-G/Version#is-version-of> 	?graph .
    }
  converg-8.rq: |
    SELECT ?version ?p1 ?o1 WHERE {
        GRAPH ?vg {
          <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/instances/ProductFeature287> ?p1 ?o1 .
        }
        ?vg <https://github.com/VCityTeam/ConVer-G/Version#is-in-version> 	?version .
    }
  converg-9.rq: |
    SELECT ?vg (MAX(?rating) as ?maxrating) WHERE {
      GRAPH ?vg {
        ?review <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/rating4> ?rating ;
          a <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/Review> .
      }
    } GROUP BY (?vg)
  converg-10.rq: |
    PREFIX vers: <https://github.com/VCityTeam/ConVer-G/Version#>
    SELECT ?graph (COUNT(?rating) as ?countrating) WHERE {
      GRAPH ?vg {
        ?review <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/rating4> ?rating ;
          a <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/Review> .
      }
        ?vg vers:is-version-of ?graph .
    } GROUP BY ?graph
  converg-11.rq: |
    PREFIX vers: <https://github.com/VCityTeam/ConVer-G/Version#>
    SELECT ?version (AVG(?rating) as ?avgrating) WHERE {
      GRAPH ?vg {
        ?review <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/rating4> ?rating ;
          a <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/Review> .
      }
      ?vg vers:is-in-version ?version .
    } GROUP BY ?version
