apiVersion: v1
kind: ConfigMap
metadata:
  name: query-script-configmap
data:
  query-dataset-theoretical.sh: |
    # /bin/bash

    printf "\n%s$(date +%FT%T) - [Query - Blazegraph] Query started."

    find . -type f -name "blazegraph*.rq" -print0 | while IFS= read -r -d '' file
    do
        printf "\n%s$(date +%FT%T) - [Query - Blazegraph] Query $file"
        name=$(basename "$file")

        start_query_triple=$(date +%s%3N)

        curl --location http://blazegraph:9999/blazegraph/namespace/kb/sparql -X POST --data-binary @"$file" \
          --header 'Content-Type: application/sparql-query' \
          --output "blazegraph/$name.json" \
          --header 'Accept: application/sparql-results+json'

        end_query_triple=$(date +%s%3N)
        printf "[Measure] (Query triple Query %s): %s ms\n" "$file" "$((end_query_triple-start_query_triple))s"
    done

    printf "\n%s$(date +%FT%T) - [Query - Blazegraph] Query completed."
  query-dataset-relational.sh: |
    # /bin/bash

    printf "\n%s$(date +%FT%T) - [quads-query] Query started."

    find . -type f -name "converg*.rq" -print0 | while IFS= read -r -d '' file
    do
        printf "\n%s$(date +%FT%T) - [quads-query] Query $file"
        name=$(basename "$file")

        start_query_relational=$(date +%s%3N)

        content=$(cat "$file")
        curl --location 'http://quads-query:8081/rdf/query' \
          --header 'Content-Type: application/sparql-query' \
          --header 'Accept: application/sparql-results+json' \
          --output "converg/$name.json" \
          --data "$content"

        end_query_relational=$(date +%s%3N)
        printf "[Measure] (Query ConVer-G Query %s): %s ms\n" "$file" "$((end_query_relational-start_query_relational))s"
    done

    printf "\n%s$(date +%FT%T) - [quads-query] Query completed."