kind: Secret
apiVersion: v1
metadata:
  name: sparql-to-sql-secret
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_DB: c3BhcnFsdG9zcWw=
  POSTGRES_PASSWORD: cGFzc3dvcmQ=
# FIXME : Modifier les identifiants