services:
  postgres:
    image: postgres@sha256:4ec37d2a07a0067f176fdcc9d4bb633a5724d2cc4f892c7a2046d054bb6939e5
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=converg
    volumes:
      - pg-volume:/var/lib/postgresql/data

  quads-loader:
    image: vcity/quads-loader
    depends_on:
      - postgres
    environment:
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/converg"
      - "SPRING_DATASOURCE_USERNAME=postgres"
      - "SPRING_DATASOURCE_PASSWORD=password"
    ports:
      - "8080:8080"

  quads-query:
    image: vcity/quads-query
    depends_on:
      - postgres
    environment:
      - "DATASOURCE_URL=jdbc:postgresql://postgres:5432/converg"
      - "DATASOURCE_USERNAME=postgres"
      - "DATASOURCE_PASSWORD=password"
      - "CONDENSED_MODE=true"
    ports:
      - "8081:8081"

  quads-vizualizer:
    image: vcity/quads-vizualizer
    depends_on:
      - quads-query
      - quads-loader
    ports:
      - "80:80"
    environment:
      - "VITE_QUERY_ENDPOINT=http://localhost:8081/rdf/query"
      - "VITE_LOADER_ENDPOINT=http://localhost:8080/import/metadata"

  quads-creator:
    image: hemoreg/weather-forecast
    depends_on:
      - quads-loader
    environment:
      - "QUADS_LOADER_URL=http://quads-loader:8080/"
      - "MODE=server"
    ports:
      - "5000:5000"

volumes:
  pg-volume:
    driver: local