apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-prometheus-exporter
spec:
  selector:
    matchLabels:
      app: postgres-prometheus-exporter
  template:
    metadata:
      labels:
        app: postgres-prometheus-exporter
    spec:
      containers:
        - name: postgres-exporter
          image: quay.io/prometheuscommunity/postgres-exporter
          ports:
            - containerPort: 9187
          env:
            - name: DATA_SOURCE_USER
              valueFrom:
                secretKeyRef:
                  name: postgresql-db-secret
                  key: POSTGRES_USER
            - name: DATA_SOURCE_PASS
              valueFrom:
                secretKeyRef:
                  name: postgresql-db-secret
                  key: POSTGRES_PASSWORD
            - name: DATA_SOURCE_URI
              valueFrom:
                secretKeyRef:
                  name: postgresql-db-secret
                  key: DATASOURCE_URL
          args:
            - "--web.listen-address=:9187"
            - "--web.telemetry-path=/metrics"
            - "--extend.query-path=/queries.yaml"
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-prometheus-exporter
spec:
  selector:
    app: postgres-prometheus-exporter
  ports:
    - protocol: TCP
      port: 9187
      targetPort: 9187