apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgres
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  strategy: {}
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: sparql-to-sql-secret
                  key: POSTGRES_DB
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sparql-to-sql-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: sparql-to-sql-secret
                  key: POSTGRES_USER
          image: postgres:15
          name: postgres
          ports:
            - containerPort: 5432
          resources: {}
          volumeMounts:
            - name: postgres-volume
              mountPath: /var/lib/postgresql
            - name: postgres-configmap-volume
              mountPath: /docker-entrypoint-initdb.d
      restartPolicy: Always
      volumes:
        - name: postgres-volume
          persistentVolumeClaim:
            claimName: postgres-volume
        - name: postgres-configmap-volume
          configMap:
            name: init-config